name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/latest/download/hugo_extended_$(uname -s)_$(uname -m).tar.gz
          tar -xvzf hugo_extended_$(uname -s)_$(uname -m).tar.gz
          sudo mv hugo /usr/local/bin/

      - name: Build Site with Hugo
        run: |
          hugo --gc --verbose --baseURL ${{ github.repository }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          cname: rizin.re
